language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
#  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_script:
  - php vendor/bin/coveralls

script: phpunit

notifications:
  email:
    recipients:
      - cameronmanderson@gmail.com